spring:
  datasource:
    username: us
    url: jdbc:h2:file:./temdb
    driverClassName: org.h2.Driver
    password: pa
  h2:
    console:
      enabled: 'true'
      settings:
        web-allow-others: 'true'
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

#verifica que la password contenga al menos una letra, al menos un numero y tenga una longitud minima de 8 caracteres
password.regex: '^(?=.*[a-zA-Z])(?=.*\d).{8,}.*$'

jwt:
  secret: 'sEcrEt123456'
#para swagger:
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
server:
  port: '8080'

